template: testify
formatter: goimports
force-file-write: true
packages:
  github.com/edocsss/agent-whiteboard/internal/common:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      pkgname: mocks
    interfaces:
      Clock:
        config:
          filename: mock_clock.go
          structname: MockClock
      IDGenerator:
        config:
          filename: mock_id_generator.go
          structname: MockIDGenerator
  github.com/edocsss/agent-whiteboard/internal/whiteboard:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      pkgname: mocks
    interfaces:
      Store:
        config:
          filename: mock_store.go
          structname: MockStore
  github.com/edocsss/agent-whiteboard/internal/image:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      pkgname: mocks
    interfaces:
      Store:
        config:
          filename: mock_store.go
          structname: MockStore
