// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/edocsss/agent-whiteboard/internal/http"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateImages provides a mock function for the type MockClient
func (_mock *MockClient) CreateImages(context1 context.Context, files []http.File, n *int64) ([]http.Resource, error) {
	ret := _mock.Called(context1, files, n)

	if len(ret) == 0 {
		panic("no return value specified for CreateImages")
	}

	var r0 []http.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []http.File, *int64) ([]http.Resource, error)); ok {
		return returnFunc(context1, files, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []http.File, *int64) []http.Resource); ok {
		r0 = returnFunc(context1, files, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]http.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []http.File, *int64) error); ok {
		r1 = returnFunc(context1, files, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImages'
type MockClient_CreateImages_Call struct {
	*mock.Call
}

// CreateImages is a helper method to define mock.On call
//   - context1 context.Context
//   - files []http.File
//   - n *int64
func (_e *MockClient_Expecter) CreateImages(context1 any, files any, n any) *MockClient_CreateImages_Call {
	return &MockClient_CreateImages_Call{Call: _e.mock.On("CreateImages", context1, files, n)}
}

func (_c *MockClient_CreateImages_Call) Run(run func(context1 context.Context, files []http.File, n *int64)) *MockClient_CreateImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []http.File
		if args[1] != nil {
			arg1 = args[1].([]http.File)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CreateImages_Call) Return(resources []http.Resource, err error) *MockClient_CreateImages_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *MockClient_CreateImages_Call) RunAndReturn(run func(context1 context.Context, files []http.File, n *int64) ([]http.Resource, error)) *MockClient_CreateImages_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWhiteboard provides a mock function for the type MockClient
func (_mock *MockClient) CreateWhiteboard(context1 context.Context, whiteboardKind http.WhiteboardKind, file http.File, n *int64) (http.Resource, error) {
	ret := _mock.Called(context1, whiteboardKind, file, n)

	if len(ret) == 0 {
		panic("no return value specified for CreateWhiteboard")
	}

	var r0 http.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.WhiteboardKind, http.File, *int64) (http.Resource, error)); ok {
		return returnFunc(context1, whiteboardKind, file, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.WhiteboardKind, http.File, *int64) http.Resource); ok {
		r0 = returnFunc(context1, whiteboardKind, file, n)
	} else {
		r0 = ret.Get(0).(http.Resource)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, http.WhiteboardKind, http.File, *int64) error); ok {
		r1 = returnFunc(context1, whiteboardKind, file, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateWhiteboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWhiteboard'
type MockClient_CreateWhiteboard_Call struct {
	*mock.Call
}

// CreateWhiteboard is a helper method to define mock.On call
//   - context1 context.Context
//   - whiteboardKind http.WhiteboardKind
//   - file http.File
//   - n *int64
func (_e *MockClient_Expecter) CreateWhiteboard(context1 any, whiteboardKind any, file any, n any) *MockClient_CreateWhiteboard_Call {
	return &MockClient_CreateWhiteboard_Call{Call: _e.mock.On("CreateWhiteboard", context1, whiteboardKind, file, n)}
}

func (_c *MockClient_CreateWhiteboard_Call) Run(run func(context1 context.Context, whiteboardKind http.WhiteboardKind, file http.File, n *int64)) *MockClient_CreateWhiteboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 http.WhiteboardKind
		if args[1] != nil {
			arg1 = args[1].(http.WhiteboardKind)
		}
		var arg2 http.File
		if args[2] != nil {
			arg2 = args[2].(http.File)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateWhiteboard_Call) Return(resource http.Resource, err error) *MockClient_CreateWhiteboard_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockClient_CreateWhiteboard_Call) RunAndReturn(run func(context1 context.Context, whiteboardKind http.WhiteboardKind, file http.File, n *int64) (http.Resource, error)) *MockClient_CreateWhiteboard_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImage provides a mock function for the type MockClient
func (_mock *MockClient) DeleteImage(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type MockClient_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockClient_Expecter) DeleteImage(context1 any, s any) *MockClient_DeleteImage_Call {
	return &MockClient_DeleteImage_Call{Call: _e.mock.On("DeleteImage", context1, s)}
}

func (_c *MockClient_DeleteImage_Call) Run(run func(context1 context.Context, s string)) *MockClient_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_DeleteImage_Call) Return(err error) *MockClient_DeleteImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteImage_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockClient_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWhiteboard provides a mock function for the type MockClient
func (_mock *MockClient) DeleteWhiteboard(context1 context.Context, whiteboardKind http.WhiteboardKind, s string) error {
	ret := _mock.Called(context1, whiteboardKind, s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWhiteboard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.WhiteboardKind, string) error); ok {
		r0 = returnFunc(context1, whiteboardKind, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteWhiteboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWhiteboard'
type MockClient_DeleteWhiteboard_Call struct {
	*mock.Call
}

// DeleteWhiteboard is a helper method to define mock.On call
//   - context1 context.Context
//   - whiteboardKind http.WhiteboardKind
//   - s string
func (_e *MockClient_Expecter) DeleteWhiteboard(context1 any, whiteboardKind any, s any) *MockClient_DeleteWhiteboard_Call {
	return &MockClient_DeleteWhiteboard_Call{Call: _e.mock.On("DeleteWhiteboard", context1, whiteboardKind, s)}
}

func (_c *MockClient_DeleteWhiteboard_Call) Run(run func(context1 context.Context, whiteboardKind http.WhiteboardKind, s string)) *MockClient_DeleteWhiteboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 http.WhiteboardKind
		if args[1] != nil {
			arg1 = args[1].(http.WhiteboardKind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_DeleteWhiteboard_Call) Return(err error) *MockClient_DeleteWhiteboard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteWhiteboard_Call) RunAndReturn(run func(context1 context.Context, whiteboardKind http.WhiteboardKind, s string) error) *MockClient_DeleteWhiteboard_Call {
	_c.Call.Return(run)
	return _c
}

// PublicURL provides a mock function for the type MockClient
func (_mock *MockClient) PublicURL(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for PublicURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_PublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicURL'
type MockClient_PublicURL_Call struct {
	*mock.Call
}

// PublicURL is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) PublicURL(s any) *MockClient_PublicURL_Call {
	return &MockClient_PublicURL_Call{Call: _e.mock.On("PublicURL", s)}
}

func (_c *MockClient_PublicURL_Call) Run(run func(s string)) *MockClient_PublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_PublicURL_Call) Return(s1 string, err error) *MockClient_PublicURL_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockClient_PublicURL_Call) RunAndReturn(run func(s string) (string, error)) *MockClient_PublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImage provides a mock function for the type MockClient
func (_mock *MockClient) UpdateImage(context1 context.Context, s string, file http.File, n *int64) (http.Resource, error) {
	ret := _mock.Called(context1, s, file, n)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImage")
	}

	var r0 http.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, http.File, *int64) (http.Resource, error)); ok {
		return returnFunc(context1, s, file, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, http.File, *int64) http.Resource); ok {
		r0 = returnFunc(context1, s, file, n)
	} else {
		r0 = ret.Get(0).(http.Resource)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, http.File, *int64) error); ok {
		r1 = returnFunc(context1, s, file, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImage'
type MockClient_UpdateImage_Call struct {
	*mock.Call
}

// UpdateImage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - file http.File
//   - n *int64
func (_e *MockClient_Expecter) UpdateImage(context1 any, s any, file any, n any) *MockClient_UpdateImage_Call {
	return &MockClient_UpdateImage_Call{Call: _e.mock.On("UpdateImage", context1, s, file, n)}
}

func (_c *MockClient_UpdateImage_Call) Run(run func(context1 context.Context, s string, file http.File, n *int64)) *MockClient_UpdateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 http.File
		if args[2] != nil {
			arg2 = args[2].(http.File)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_UpdateImage_Call) Return(resource http.Resource, err error) *MockClient_UpdateImage_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockClient_UpdateImage_Call) RunAndReturn(run func(context1 context.Context, s string, file http.File, n *int64) (http.Resource, error)) *MockClient_UpdateImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWhiteboard provides a mock function for the type MockClient
func (_mock *MockClient) UpdateWhiteboard(context1 context.Context, whiteboardKind http.WhiteboardKind, s string, file http.File, n *int64) (http.Resource, error) {
	ret := _mock.Called(context1, whiteboardKind, s, file, n)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWhiteboard")
	}

	var r0 http.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.WhiteboardKind, string, http.File, *int64) (http.Resource, error)); ok {
		return returnFunc(context1, whiteboardKind, s, file, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.WhiteboardKind, string, http.File, *int64) http.Resource); ok {
		r0 = returnFunc(context1, whiteboardKind, s, file, n)
	} else {
		r0 = ret.Get(0).(http.Resource)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, http.WhiteboardKind, string, http.File, *int64) error); ok {
		r1 = returnFunc(context1, whiteboardKind, s, file, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateWhiteboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWhiteboard'
type MockClient_UpdateWhiteboard_Call struct {
	*mock.Call
}

// UpdateWhiteboard is a helper method to define mock.On call
//   - context1 context.Context
//   - whiteboardKind http.WhiteboardKind
//   - s string
//   - file http.File
//   - n *int64
func (_e *MockClient_Expecter) UpdateWhiteboard(context1 any, whiteboardKind any, s any, file any, n any) *MockClient_UpdateWhiteboard_Call {
	return &MockClient_UpdateWhiteboard_Call{Call: _e.mock.On("UpdateWhiteboard", context1, whiteboardKind, s, file, n)}
}

func (_c *MockClient_UpdateWhiteboard_Call) Run(run func(context1 context.Context, whiteboardKind http.WhiteboardKind, s string, file http.File, n *int64)) *MockClient_UpdateWhiteboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 http.WhiteboardKind
		if args[1] != nil {
			arg1 = args[1].(http.WhiteboardKind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 http.File
		if args[3] != nil {
			arg3 = args[3].(http.File)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_UpdateWhiteboard_Call) Return(resource http.Resource, err error) *MockClient_UpdateWhiteboard_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockClient_UpdateWhiteboard_Call) RunAndReturn(run func(context1 context.Context, whiteboardKind http.WhiteboardKind, s string, file http.File, n *int64) (http.Resource, error)) *MockClient_UpdateWhiteboard_Call {
	_c.Call.Return(run)
	return _c
}
