// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReadiness creates a new instance of MockReadiness. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadiness(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadiness {
	mock := &MockReadiness{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadiness is an autogenerated mock type for the Readiness type
type MockReadiness struct {
	mock.Mock
}

type MockReadiness_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadiness) EXPECT() *MockReadiness_Expecter {
	return &MockReadiness_Expecter{mock: &_m.Mock}
}

// Ready provides a mock function for the type MockReadiness
func (_mock *MockReadiness) Ready(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReadiness_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockReadiness_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockReadiness_Expecter) Ready(context1 any) *MockReadiness_Ready_Call {
	return &MockReadiness_Ready_Call{Call: _e.mock.On("Ready", context1)}
}

func (_c *MockReadiness_Ready_Call) Run(run func(context1 context.Context)) *MockReadiness_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadiness_Ready_Call) Return(err error) *MockReadiness_Ready_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReadiness_Ready_Call) RunAndReturn(run func(context1 context.Context) error) *MockReadiness_Ready_Call {
	_c.Call.Return(run)
	return _c
}
