// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/edocsss/agent-whiteboard/internal/whiteboard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStore
func (_mock *MockStore) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return(err error) *MockStore_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func() error) *MockStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockStore
func (_mock *MockStore) Create(context1 context.Context, whiteboard1 whiteboard.Whiteboard) error {
	ret := _mock.Called(context1, whiteboard1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.Whiteboard) error); ok {
		r0 = returnFunc(context1, whiteboard1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - whiteboard1 whiteboard.Whiteboard
func (_e *MockStore_Expecter) Create(context1 any, whiteboard1 any) *MockStore_Create_Call {
	return &MockStore_Create_Call{Call: _e.mock.On("Create", context1, whiteboard1)}
}

func (_c *MockStore_Create_Call) Run(run func(context1 context.Context, whiteboard1 whiteboard.Whiteboard)) *MockStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 whiteboard.Whiteboard
		if args[1] != nil {
			arg1 = args[1].(whiteboard.Whiteboard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Create_Call) Return(err error) *MockStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Create_Call) RunAndReturn(run func(context1 context.Context, whiteboard1 whiteboard.Whiteboard) error) *MockStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStore
func (_mock *MockStore) Delete(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) Delete(context1 any, s any) *MockStore_Delete_Call {
	return &MockStore_Delete_Call{Call: _e.mock.On("Delete", context1, s)}
}

func (_c *MockStore_Delete_Call) Run(run func(context1 context.Context, s string)) *MockStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Delete_Call) Return(err error) *MockStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Delete_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStore
func (_mock *MockStore) Get(context1 context.Context, s string) (whiteboard.Whiteboard, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 whiteboard.Whiteboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (whiteboard.Whiteboard, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) whiteboard.Whiteboard); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(whiteboard.Whiteboard)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) Get(context1 any, s any) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *MockStore_Get_Call) Run(run func(context1 context.Context, s string)) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(whiteboard1 whiteboard.Whiteboard, err error) *MockStore_Get_Call {
	_c.Call.Return(whiteboard1, err)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (whiteboard.Whiteboard, error)) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function for the type MockStore
func (_mock *MockStore) Ready(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockStore_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockStore_Expecter) Ready(context1 any) *MockStore_Ready_Call {
	return &MockStore_Ready_Call{Call: _e.mock.On("Ready", context1)}
}

func (_c *MockStore_Ready_Call) Run(run func(context1 context.Context)) *MockStore_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Ready_Call) Return(err error) *MockStore_Ready_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Ready_Call) RunAndReturn(run func(context1 context.Context) error) *MockStore_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type MockStore
func (_mock *MockStore) Replace(context1 context.Context, whiteboard1 whiteboard.Whiteboard) error {
	ret := _mock.Called(context1, whiteboard1)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.Whiteboard) error); ok {
		r0 = returnFunc(context1, whiteboard1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockStore_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - context1 context.Context
//   - whiteboard1 whiteboard.Whiteboard
func (_e *MockStore_Expecter) Replace(context1 any, whiteboard1 any) *MockStore_Replace_Call {
	return &MockStore_Replace_Call{Call: _e.mock.On("Replace", context1, whiteboard1)}
}

func (_c *MockStore_Replace_Call) Run(run func(context1 context.Context, whiteboard1 whiteboard.Whiteboard)) *MockStore_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 whiteboard.Whiteboard
		if args[1] != nil {
			arg1 = args[1].(whiteboard.Whiteboard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Replace_Call) Return(err error) *MockStore_Replace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Replace_Call) RunAndReturn(run func(context1 context.Context, whiteboard1 whiteboard.Whiteboard) error) *MockStore_Replace_Call {
	_c.Call.Return(run)
	return _c
}
