// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/edocsss/agent-whiteboard/internal/whiteboard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperations creates a new instance of MockOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperations {
	mock := &MockOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperations is an autogenerated mock type for the Operations type
type MockOperations struct {
	mock.Mock
}

type MockOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperations) EXPECT() *MockOperations_Expecter {
	return &MockOperations_Expecter{mock: &_m.Mock}
}

// CreateHTML provides a mock function for the type MockOperations
func (_mock *MockOperations) CreateHTML(context1 context.Context, createInput whiteboard.CreateInput) (whiteboard.Result, error) {
	ret := _mock.Called(context1, createInput)

	if len(ret) == 0 {
		panic("no return value specified for CreateHTML")
	}

	var r0 whiteboard.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.CreateInput) (whiteboard.Result, error)); ok {
		return returnFunc(context1, createInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.CreateInput) whiteboard.Result); ok {
		r0 = returnFunc(context1, createInput)
	} else {
		r0 = ret.Get(0).(whiteboard.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, whiteboard.CreateInput) error); ok {
		r1 = returnFunc(context1, createInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_CreateHTML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHTML'
type MockOperations_CreateHTML_Call struct {
	*mock.Call
}

// CreateHTML is a helper method to define mock.On call
//   - context1 context.Context
//   - createInput whiteboard.CreateInput
func (_e *MockOperations_Expecter) CreateHTML(context1 any, createInput any) *MockOperations_CreateHTML_Call {
	return &MockOperations_CreateHTML_Call{Call: _e.mock.On("CreateHTML", context1, createInput)}
}

func (_c *MockOperations_CreateHTML_Call) Run(run func(context1 context.Context, createInput whiteboard.CreateInput)) *MockOperations_CreateHTML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 whiteboard.CreateInput
		if args[1] != nil {
			arg1 = args[1].(whiteboard.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperations_CreateHTML_Call) Return(result whiteboard.Result, err error) *MockOperations_CreateHTML_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockOperations_CreateHTML_Call) RunAndReturn(run func(context1 context.Context, createInput whiteboard.CreateInput) (whiteboard.Result, error)) *MockOperations_CreateHTML_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMarkdown provides a mock function for the type MockOperations
func (_mock *MockOperations) CreateMarkdown(context1 context.Context, createInput whiteboard.CreateInput) (whiteboard.Result, error) {
	ret := _mock.Called(context1, createInput)

	if len(ret) == 0 {
		panic("no return value specified for CreateMarkdown")
	}

	var r0 whiteboard.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.CreateInput) (whiteboard.Result, error)); ok {
		return returnFunc(context1, createInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.CreateInput) whiteboard.Result); ok {
		r0 = returnFunc(context1, createInput)
	} else {
		r0 = ret.Get(0).(whiteboard.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, whiteboard.CreateInput) error); ok {
		r1 = returnFunc(context1, createInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_CreateMarkdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMarkdown'
type MockOperations_CreateMarkdown_Call struct {
	*mock.Call
}

// CreateMarkdown is a helper method to define mock.On call
//   - context1 context.Context
//   - createInput whiteboard.CreateInput
func (_e *MockOperations_Expecter) CreateMarkdown(context1 any, createInput any) *MockOperations_CreateMarkdown_Call {
	return &MockOperations_CreateMarkdown_Call{Call: _e.mock.On("CreateMarkdown", context1, createInput)}
}

func (_c *MockOperations_CreateMarkdown_Call) Run(run func(context1 context.Context, createInput whiteboard.CreateInput)) *MockOperations_CreateMarkdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 whiteboard.CreateInput
		if args[1] != nil {
			arg1 = args[1].(whiteboard.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperations_CreateMarkdown_Call) Return(result whiteboard.Result, err error) *MockOperations_CreateMarkdown_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockOperations_CreateMarkdown_Call) RunAndReturn(run func(context1 context.Context, createInput whiteboard.CreateInput) (whiteboard.Result, error)) *MockOperations_CreateMarkdown_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockOperations
func (_mock *MockOperations) Delete(context1 context.Context, kind whiteboard.Kind, s string) error {
	ret := _mock.Called(context1, kind, s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.Kind, string) error); ok {
		r0 = returnFunc(context1, kind, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperations_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOperations_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - kind whiteboard.Kind
//   - s string
func (_e *MockOperations_Expecter) Delete(context1 any, kind any, s any) *MockOperations_Delete_Call {
	return &MockOperations_Delete_Call{Call: _e.mock.On("Delete", context1, kind, s)}
}

func (_c *MockOperations_Delete_Call) Run(run func(context1 context.Context, kind whiteboard.Kind, s string)) *MockOperations_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 whiteboard.Kind
		if args[1] != nil {
			arg1 = args[1].(whiteboard.Kind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperations_Delete_Call) Return(err error) *MockOperations_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperations_Delete_Call) RunAndReturn(run func(context1 context.Context, kind whiteboard.Kind, s string) error) *MockOperations_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockOperations
func (_mock *MockOperations) Get(context1 context.Context, s string) (whiteboard.Whiteboard, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 whiteboard.Whiteboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (whiteboard.Whiteboard, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) whiteboard.Whiteboard); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(whiteboard.Whiteboard)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOperations_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockOperations_Expecter) Get(context1 any, s any) *MockOperations_Get_Call {
	return &MockOperations_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *MockOperations_Get_Call) Run(run func(context1 context.Context, s string)) *MockOperations_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperations_Get_Call) Return(whiteboard1 whiteboard.Whiteboard, err error) *MockOperations_Get_Call {
	_c.Call.Return(whiteboard1, err)
	return _c
}

func (_c *MockOperations_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (whiteboard.Whiteboard, error)) *MockOperations_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOperations
func (_mock *MockOperations) Update(context1 context.Context, updateInput whiteboard.UpdateInput) (whiteboard.Result, error) {
	ret := _mock.Called(context1, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 whiteboard.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.UpdateInput) (whiteboard.Result, error)); ok {
		return returnFunc(context1, updateInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.UpdateInput) whiteboard.Result); ok {
		r0 = returnFunc(context1, updateInput)
	} else {
		r0 = ret.Get(0).(whiteboard.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, whiteboard.UpdateInput) error); ok {
		r1 = returnFunc(context1, updateInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperations_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOperations_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - updateInput whiteboard.UpdateInput
func (_e *MockOperations_Expecter) Update(context1 any, updateInput any) *MockOperations_Update_Call {
	return &MockOperations_Update_Call{Call: _e.mock.On("Update", context1, updateInput)}
}

func (_c *MockOperations_Update_Call) Run(run func(context1 context.Context, updateInput whiteboard.UpdateInput)) *MockOperations_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 whiteboard.UpdateInput
		if args[1] != nil {
			arg1 = args[1].(whiteboard.UpdateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperations_Update_Call) Return(result whiteboard.Result, err error) *MockOperations_Update_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockOperations_Update_Call) RunAndReturn(run func(context1 context.Context, updateInput whiteboard.UpdateInput) (whiteboard.Result, error)) *MockOperations_Update_Call {
	_c.Call.Return(run)
	return _c
}
